### ISSUE TITLE
Doesn't explicitly say to clone the repo

### ISSUE THREAD

**Issue by BenitolSantos** [learn-co-curriculum/rails-application-basics-readme#16] opened 2019-05-10 15:30 UTC
"Yep, that's the problem. You have to fork and then clone down the repo to your local computer and be inside of it" - Johnathan Chriest May 10, 2019 11:28am EST

**Comment by drakeltheryuujin** [comment] 2019-10-11 15:51
Hi there,

I'm unable to reproduce or decipher if this is related to this README, so I'm going to close it for now. If this is related to this lesson, could you provide a bit more detail about the issue?
Thanks! 💙

**Closed as completed by drakeltheryuujin** 2019-10-11 15:51 UTC
